# SAM deploy defaults (override with --config-env)
version = 0.1

[default.deploy.parameters]
stack_name = "ssv-validator"
resolve_s3 = true
s3_prefix = "ssv-validator"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev"

[default.build.parameters]
cached = true
parallel = true
